resolver: lts-18.6

packages:
  - '.'
  - xmonad
  - xmonad-contrib

extra-deps: 
  - xmobar-0.37@sha256:42cfb68788901364a1b4ddfdc213106e18851dda2575420e532ee31c4cce4e51,12020


flags: {}
extra-package-dbs: []

nix:
    packages:
      - pkgconfig
      - autoconf
      - gcc
      - xorg.libX11
      - xorg.libXext
      - xorg.libXft
      - xorg.libXinerama
      - xorg.libXpm
      - xorg.libXrandr
      - xorg.libXrender
      - xorg.libXScrnSaver
